[package]
name = "radish"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
ctrlc = { version = "3.4.5", features = ["termination"] }
http = "1.2.0"
httparse = "1.9.5"
smol = "2.0.2"
